[package]
publish = false
name = "typescript-wasi"
version = { workspace = true }
edition = { workspace = true }
authors = { workspace = true }
description = "Rusty TypeScript runtime exported as WASI module"
license = { workspace = true }

[lib]
crate-type = ["cdylib"]

[dependencies]
serde = { workspace = true, features = ["derive"] }
log = { workspace = true }
serde_json = { workspace = true }

[target.wasm32-wasip2.dependencies]
wit-bindgen = { version = "0.15.0", features = ["macros"] }



